### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by kwhuang88228** [facebookresearch/mae#66]
Also having the same issue as #55 and #57 when running pretrain. I have /checkpoint, /checkpoint/{USER} and /checkpoint/{USER}/experiments. Unclear how to set up --job_dir and getting the following error. Any updates or suggestions? Appreciate any help!

Traceback (most recent call last):
  File "submitit_pretrain.py", line 131, in <module>
    main()
  File "submitit_pretrain.py", line 120, in main
    args.dist_url = get_init_file().as_uri()
  File "/anaconda/envs/mae/lib/python3.6/pathlib.py", line 721, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI

**Comment by RyanZRH** [comment]
hello, did you solve it? i also meet this problem

**Comment by kwhuang88228** [comment]
It's been a while but iirc I just commented out a couple lines and everything compiled

**Comment by funkyZhaofour** [comment]
I think this error is because the "p" returned from "get_shared_folder()" is a relative path, but not a absolute path. 

So I solve it with this:

def get_shared_folder() -> Path:
    user = os.getenv("USER")
    cur_file_path = Path("checkpoint").absolute()
    if Path("checkpoint/").is_dir():
        p = Path(f"{cur_file_path}/{user}/experiments")
        p.mkdir(exist_ok=True)
        return p
    raise RuntimeError("No shared folder available")

**Comment by chos1npc** [comment]
Excuse I have the same issue, but I can't solve it. I try to create check point, but I think I wrong.
